Shop Ban Sach/ShopQuocViet/Controllers/ChiTietSPController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ShopQuocViet.Models;

namespace ShopQuocViet.Controllers
{

    public class ChiTietSPController : Controller
    {
        BookModel1 db = new BookModel1();
        // GET: ChiTietSP
       
        public ActionResult Index(string id)
        {
            string MaKH = "";
            if (Session["TaiKhoan"] != null)
            {
                NguoiDung ND = (NguoiDung)Session["TaiKhoan"];
                MaKH = ND.TenDN;
            }
            ViewBag.MaND = MaKH;
            var CTSach = db.TTSach.Where(n => n.MaSach == id).ToList();
            if(CTSach.Count != 0)
            {
                ViewBag.MaCD = CTSach[0].MaCD;
                ViewBag.MaSach = id;
                var DanhGia = db.DanhGia.Where(m => m.MaSach == id).Where(m => m.MaND == MaKH).ToList();
                if(DanhGia.Count() != 0)
                {
                    ViewBag.SoSao = DanhGia[0].SoSao;
                }
                return View(CTSach);
            }
            else
            {
                return RedirectToAction("ThongBao");
            }
           
        }
        public ActionResult AnhKem()
        {
            var CTSach = db.ANH.SqlQuery("SELECT *from Anh WHERE MaSach is null").ToList();
            return PartialView(CTSach);
        }
        public ActionResult ThongBao()
        {
            return PartialView();
        }
        [ChildActionOnly]
        public ActionResult SachCungCD(string maCD)
        {
            var ListSach = db.TTSach.Where(s=> s.MaCD == maCD).ToList();
            return PartialView("~/Views/Home/PartialSachNoiBat.cshtml", ListSach);
        }
        [HttpPost]
        public ActionResult DanhGia(int star, string maSach)
        {
            NguoiDung ND = (NguoiDung)Session["TaiKhoan"];
            var DanhGiaVeSach = db.DanhGia.Where(s=>s.MaSach == maSach).Where(s=>s.MaND == ND.TenDN).ToList();
            if(DanhGiaVeSach.Count !=  0)
            {
                DanhGiaVeSach[0].SoSao = star;
            }
            else
            {
                DanhGia dg = new DanhGia();
                dg.MaND = ND.TenDN;
                dg.MaSach = maSach;
                dg.SoSao = star;
                db.DanhGia.Add(dg);
            }
            db.SaveChanges();
            var sumStar = 0;
            var Star = db.DanhGia.Where(m => m.MaSach == maSach).ToList();
            
            foreach (var item in Star)
            {
                sumStar += Convert.ToInt32(item.SoSao);
            }
            sumStar = Convert.ToInt32(sumStar / Star.Count());
               
            var Sach = db.Sach.Where(m => m.MaSach == maSach).ToList();
            Sach[0].DanhGia = sumStar;
            db.SaveChanges();
            return null;
        }
     
    }
}

Shop Ban Sach/ShopQuocViet/Views/ChiTietSP/AnhKem.cshtml
@using ShopQuocViet.Models
@model List<ANH>
    @foreach (var item in Model)
    {
        <img src="~/Content/images/@item.PathAnh" style="width:15%" class="anhKemSP" />
    }

Shop Ban Sach/ShopQuocViet/Views/ChiTietSP/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using ShopQuocViet.Models;
@model List<TTSach>
@foreach (var item in Model)
{
<section>
    <div class="contentChiTiet">
        <div class="container">
            <div class="row">
                <div class="col-sm-1">

                </div>
                <div class="col-sm-10">
                    <div class="breadcrumb">
                        <div class="container">
                          <a class="breadcrumb-item" href="~/Home/Index">Shop Quốc Việt</a>
                                <a class="breadcrumb-item" href="~/DanhMucSP/Index">Danh mục sách</a>
                                <a class="breadcrumb-item" name = "TenCD" href="@Url.Action("Index","DanhSachSP",new {maCD = @item.MaCD})">@item.TenCD</a>
                                <span class="breadcrumb-item active">@item.TenSach</span> 

                        </div>
                    </div>
                    <section class="product-sec">
                        <div class="container khungSPDon">
                                <div class="row">
                                    <div class="col-md-7" style="text-align:justify">
                                        <div class="row singleProduct">
                                            <img src="~/Content/images/@item.PathAnh" style="width:40%; height: 100%" class="anhMax" />
                                        </div>
                                        <div class="row">
                                            <img src="~/Content/images/@item.PathAnh" style="width:15%" class="anhKemSP" />
                                            @Html.Action("Anhkem","ChiTietSP")
                                        </div>
                                    </div>
                                        <div class="col-md-3 col-xs-3 slider-content ThongTinSP">
                                            <ul>
                                                <li>
                                                    <h3>@item.TenSach</h3>
                                                </li>
                                                <li>
                                                    <span class="name">Giá bìa: </span><span class="clm">:</span>
                                                    <span class="price">@item.GiaBia đồng</span>
                                                </li>
                                                <li>
                                                    <span class="name">Giá bán</span><span class="clm">:</span>
                                                    <span class="price final">@item.GiaBan đồng</span>
                                                </li>
                                                <li><span class="save-cost">Tiết kiệm @item.GiamGia đồng (@Convert.ToDecimal(@item.GiamGia * 100 / @item.GiaBia)%)</span></li>
                                                <!-- 
                                                     <li>
                                                    <span class="name">Số lượng:</span>
                                                    <input class="form-control text-center" name="SoLuong" value="1" type="number" style="width: 80px">
                                                </li>
                                                 -->
                                               
                                                <li>
                                                    <span class="name">Đánh giá:</span>
                                                    @for (int i = 0; i < Convert.ToDecimal(@item.DanhGia); i++)
                                                    {
                                                        <i class="fa fa-star" style="color:orange" aria-hidden="true"></i>
                                                    }
                                                 
                                                </li>
                                              
                                            </ul>
                                            <div class="btn-sec">
                                                @Ajax.ActionLink("Thêm vào giỏ hàng", "ThemSP2", "GioHang", new { maSach = @item.MaSach}, new AjaxOptions { HttpMethod = "GET", UpdateTargetId = "ParentItem", InsertionMode = InsertionMode.Replace }, new { @class = "btn butThemVaoGioHang",onclick = "myFunction(); loadGH()" })
                                                <a href="@Url.Action("ThemSP1","GioHang",new {maSach = @item.MaSach})" class="btn black">Mua ngay</a>
                                                <div id="snackbar">Bạn đã thêm vào giỏ hàng thành công</div>
                                            </div>
                                        </div>
                                    
                                </div>
                            </div>
                        </section>
                    </div>
                </div>
            </div>
        </div>
    <div class="container">
        <div class="row">
            <div class="col-sm-1">

            </div>
            <div class="col-sm-5">
                <h2>Thông tin chi tiết</h2>
                <table class="table table-striped">
                    <tbody>
                        <tr>
                            <td><pre>Nhà xuất bản:      <b>@item.NXB</b></pre></td>
                        </tr>
                        <tr>
                            <td><pre>Chủ đề:            <b>@item.TenCD</b></pre></td>
                        </tr>
                        <tr>
                            <td><pre>Tên sách:          <b>@item.TenSach</b></pre></td>
                        </tr>
                        <tr>
                            <td><pre>Tác giả:           <b>@item.TacGia</b></pre></td>
                        </tr>
                        <tr>
                            <td><pre>Khối lượng:        <b>@item.KhoiLuong</b></pre></td>
                        </tr>
                        <tr>
                            <td><pre>Định dạng:         <b>@item.DinhDang</b></pre></td>
                        </tr>
                        <tr>
                            <td><pre>Kích thước:        <b>@item.KichThuoc</b></pre></td>
                        </tr>
                        <tr>
                            <td><pre>Số trang:          <b>@item.SoTrang</b></pre></td>
                        </tr>
                        <tr>
                            <td><pre>Ngày phát hành:    <b>@item.NgayPhatHanh.ToString().Split(' ')[0]</b></pre></td>
                        </tr>
                    </tbody>
                </table>
                <div class="stars">
                    <b>Đánh giá của bạn: </b>

                        @if (@ViewBag.MaND == "")
                        {

                            <form action="">
                               
                                <label class="star star-5" for="star-5" onclick="Request(5)"></label>
                              
                                <label class="star star-4" for="star-4" onclick="Request(4)"></label>
                               
                                <label class="star star-3" for="star-3" onclick="Request(3)"></label>
                              
                                <label class="star star-2" for="star-2" onclick="Request(2)"></label>
                               
                                <label class="star star-1" for="star-1" onclick="Request(1)"></label>
                            </form>

                        }
                        else
                        {
                            <form action="">
                                @if (ViewBag.SoSao == null)
                                {

                                <input class="star star-5" id="star-5" type="radio" onclick="Request(5); loadGH('@item.MaSach')" name="star" />
                                <label class="star star-5" for="star-5"></label>
                                <input class="star star-4" id="star-4" type="radio" onclick="Request(4); loadGH('@item.MaSach')" name="star" />
                                <label class="star star-4" for="star-4"></label>
                                <input class="star star-3" id="star-3" type="radio" onclick="Request(3); loadGH('@item.MaSach') " name="star" />
                                <label class="star star-3" for="star-3"></label>
                                <input class="star star-2" id="star-2" type="radio" onclick="Request(2); loadGH('@item.MaSach') " name="star" />
                                <label class="star star-2" for="star-2"></label>
                                <input class="star star-1" id="star-1" type="radio" onclick="Request(1); loadGH('@item.MaSach')" name="star" />
                                <label class="star star-1" for="star-1"></label>

                                }
                                else
                                {

                                    for (var i = 5; i > Convert.ToInt32(ViewBag.SoSao); i--)
                                    {
                                        <input class="star star-@i" id="star-@i" type="radio" onclick="Request(@i); loadGH('@item.MaSach')" name="star" />
                                        <label class="star star-@i" for="star-@i"></label>
                                    }
                                    for (var i = Convert.ToInt32(ViewBag.SoSao); i >= 1 ; i--)
                                    {
                                        <input class="star star-@i" id="star-@i" type="radio" onclick="Request(@i); loadGH('@item.MaSach')" name="star" />
                                        <label class="star star-@i" style="color:orange" for="star-@i"></label>
                                    }

                                }
                            </form>
                        }

                    </div>
                </div>

            <div class="col-sm-5">
                <br />
                <h3>Mô tả:</h3>
                <p>
                    @item.MoTa
                </p>
            </div>
            <div class="col-sm-1">

            </div>
        </div>
    </div>
    </section>
    <div id="snackbar1">Bạn đã đánh giá thành công</div>
}

<script>
    function Request(num) {
        var maSach = '@ViewBag.MaSach';
        var TaiKhoan = '@ViewBag.MaND';

        if (TaiKhoan == "")
        {
            alert("Đánh giá sản phẩm chỉ dành cho thành viên của shop");
            $(".star").css("color", "#000");
        }
        else
        {
            $(".star").css("color", "#000");
             $.ajax({
                 type: "POST",
                data: {
                    star: num,
                    maSach: maSach
                },
                url: '@Url.Action("DanhGia","ChiTietSP")',
                success: function () {
                    myFunction1();
               }
            });
        }

    }

    function loadGH() {
        setTimeout(function () {
              $.ajax({
                 type: "GET",
                url: '@Url.Action("SoLuongLoaiSach","GioHang")',
                success: function (response) {
                    $(".quntity").html(response);
               }
            },);
        },2000)

    }

</script>

Shop Ban Sach/ShopQuocViet/Views/ChiTietSP/ThongBao.cshtml
@{
    ViewBag.Title = "ThongBao";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<br />
<br />
<br />
<br />
<br />
<br />
<h3 style="text-align:center">Không có sản phẩm phù hợp</h3>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />