Shop Ban Sach/ShopQuocViet/Areas/Admin/Controllers/AdminHomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ShopQuocViet.Models;
using System.Web.Security;
namespace ShopQuocViet.Areas.Admin.Controllers
{
    [Authorize(Roles = "admin")]
    public class AdminHomeController : Controller
    {
        BookModel1 db = new BookModel1();
        // GET: Admin/Home
        public ActionResult Index()
        {
            var donHang = db.HoaDon.Take(4).ToList();
            ViewBag.SLCD = db.ChuDe.Count();
            ViewBag.SLSP = db.Sach.Count();
            ViewBag.SLTV = db.NguoiDung.Count();
            ViewBag.SLDH = db.HoaDon.Count();
            return View(donHang);
        }
        public ActionResult XemSP()
        {
            var ListSach = db.TTSach.ToList();
            return View(ListSach);
        }
        public ActionResult XemDM()
        {
            var ListDM = db.DanhMuc.ToList();
            return View(ListDM);
        }
        public ActionResult XemChuDe()
        {
            var ListCD = db.ChuDe.OrderBy(m=>m.MaDM).ToList();
            return View(ListCD);
        }
        public ActionResult XemDonHang()
        {
            var ListHD = db.HoaDon.OrderBy(m => m.MaHD).ToList();
            return View(ListHD);
        }
        public ActionResult ChiTietHD(string MaHD)
        {
            ViewBag.MaHD = MaHD;
            var ListCTDH = db.CTHoaDon.SqlQuery("Select *from CTHoaDon where MaHD = '"+MaHD+"'").ToList();
            if (ListCTDH != null)
            {
                return View(ListCTDH);
            }
            else
                return null;
        }
        public ActionResult ThanhVien()
        {
            var ListTV = db.NguoiDung.Where(m=>m.MaLoaiTK == "client").ToList();
            return View(ListTV);
        }
        public ActionResult Admin()
        {
            var ListTV = db.NguoiDung.Where(m => m.MaLoaiTK == "admin").ToList();
            return View(ListTV);
        }
        public ActionResult DangXuat()
        {
            FormsAuthentication.SignOut();
            Session["TaiKhoan"] = null;
            return Redirect("~/Home/Index");
        }
    }
}

Shop Ban Sach/ShopQuocViet/Areas/Admin/Views/AdminHome/Admin.cshtml
@using ShopQuocViet.Models
@model List<NguoiDung>
@{
    Layout = "~/Areas/Admin/Views/Shared/LayoutAdmin.cshtml";
}
<div class="right__content">
    <div class="right__title">Bảng điều khiển</div>
    <p class="right__desc">Xem Thành viên</p>
    <div class="right__table">
        <div class="right__tableWrapper">
            <table>
                <thead>
                    <tr>
                        <th>Tài khoản</th>
                        <th>Tên</th>
                        <th>Email</th>
                        <th>Sđt</th>
                        <th>Địa chỉ</th>
                        <th>Sửa</th>
                        <th>Xoá</th>
                    </tr>
                </thead>

                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td data-label="STT">@item.TenDN</td>
                            <td data-label="Tên">@item.TenND</td>
                            <td data-label="Email">@item.Email</td>
                            <td data-label="Phone">@item.SDT</td>
                            <td data-label="Địa chỉ">@item.DiaChi</td>
                            <td data-label="Sửa" class="right__iconTable"><a href=""><img src="~/Areas/Admin/Content/assets/icon-edit.svg" alt=""></a></td>
                            <td data-label="Xoá" class="right__iconTable"><a href="#"><img src="~/Areas/Admin/Content/assets/icon-trash-black.svg" alt=""></a></td>
                        </tr>
                    }

                </tbody>
            </table>
        </div>
    </div>
</div>

Shop Ban Sach/ShopQuocViet/Areas/Admin/Views/AdminHome/ChiTietHD.cshtml
@using ShopQuocViet.Models
@model List<CTHoaDon>
@{
    Layout = "~/Areas/Admin/Views/Shared/LayoutAdmin.cshtml";
}

<div class="right__content">
    <div class="right__title">Bảng điều khiển</div>
    <p class="right__desc">Xem chi tiết đơn hàng</p>
    <p class="right__desc">Mã đơn hàng <span style="color:orange">@ViewBag.MaHD</span></p>
    <div class="right__table">
        <div class="right__tableWrapper">
            <table>
                <thead>
                    <tr>
                        <th>Mã hóa đơn</th>
                        <th>Mã sản phẩm</th>
                        <th>Đơn giá</th>
                        <th>Số lượng</th>
                    </tr>
                </thead>

                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td class="stt" data-label="Mã hóa đơn">@item.MaHD</td>
                            <td data-label="Mã sản phẩm">@item.MaSach</td>
                            <td data-label="Đơn giá">@item.DonGia</td>
                            <td data-label="Số lượng">@item.SoLuong</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

Shop Ban Sach/ShopQuocViet/Areas/Admin/Views/AdminHome/Index.cshtml
@using ShopQuocViet.Models
@model List<HoaDon>
@{
    Layout = "~/Areas/Admin/Views/Shared/LayoutAdmin.cshtml";
}

<div class="right__content">
    <div class="right__title">Bảng điều khiển</div>
    <p class="right__desc">Bảng điều khiển</p>
    <div class="right__cards">
        <a class="right__card" href="~/Admin/AdminHome/XemSP">
            <div class="right__cardTitle">Sản Phẩm</div>
            <div class="right__cardNumber">@ViewBag.SLSP</div>
            <div class="right__cardDesc">Xem Chi Tiết <img src="~/Areas/Admin/Content/assets/arrow-right.svg" alt=""></div>
        </a>
        <a class="right__card" href="~/Admin/AdminHome/ThanhVien">
            <div class="right__cardTitle">Thành Viên</div>
            <div class="right__cardNumber">@ViewBag.SLTV</div>
            <div class="right__cardDesc">Xem Chi Tiết <img src="~/Areas/Admin/Content/assets/arrow-right.svg" alt=""></div>
        </a>
        <a class="right__card" href="~/Admin/AdminHome/XemChuDe">
            <div class="right__cardTitle">Chủ Đề</div>
            <div class="right__cardNumber">@ViewBag.SLCD</div>
            <div class="right__cardDesc">Xem Chi Tiết <img src="~/Areas/Admin/Content/assets/arrow-right.svg" alt=""></div>
        </a>
        <a class="right__card" href="~/Admin/AdminHome/XemDonHang">
            <div class="right__cardTitle">Đơn Hàng</div>
            <div class="right__cardNumber">@ViewBag.SLDH</div>
            <div class="right__cardDesc">Xem Chi Tiết <img src="~/Areas/Admin/Content/assets/arrow-right.svg" alt=""></div>
        </a>
    </div>
    <div class="right__table">
        <p class="right__tableTitle">Đơn hàng mới</p>
        <div class="right__tableWrapper">
            <table>
                <thead>
                    <tr>
                        <th>Mã hoá đơn</th>
                        <th>Tên khách hàng</th>
                        <th>Tổng tiền</th>
                        <th>Trạng thái v/c</th>
                        <th>Thanh toán</th>
                        <th>Địa chỉ </th>
                        <th>Sđt</th>
                        <th >Ngày</th>
                    </tr>
                </thead>

                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.MaHD</td>
                            <td>@item.TenKH</td>
                            <td>@Convert.ToInt32(@item.TongTien).ToString("N0")</td>
                            <td>@item.TrangThaiVC</td>
                            <td>@item.ThanhToan</td>
                            <td>@item.DiaChi</td>
                            <td>@item.SDT</td>
                            <td>@item.Ngay.ToString().Substring(0,10)</td>
                        </tr>
                    }
                    
                </tbody>
            </table>
        </div>
        <a href="" class="right__tableMore"><p>Xem tất cả các đơn đặt hàng</p> <img src="~/Areas/Admin/Content/assets/arrow-right-black.svg" alt=""></a>
    </div>
</div>

Shop Ban Sach/ShopQuocViet/Areas/Admin/Views/AdminHome/ThanhVien.cshtml
@using ShopQuocViet.Models
@model List<NguoiDung>
@{
    Layout = "~/Areas/Admin/Views/Shared/LayoutAdmin.cshtml";
}
<div class="right__content">
    <div class="right__title">Bảng điều khiển</div>
    <p class="right__desc">Xem Thành viên</p>
    <div class="right__table">
        <div class="right__tableWrapper">
            <table>
                <thead>
                    <tr>
                        <th>Tài khoản</th>
                        <th>Tên</th>
                        <th>Email</th>
                        <th>Sđt</th>
                        <th>Địa chỉ</th>
                        <th>Xoá</th>
                    </tr>
                </thead>

                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td data-label="STT">@item.TenDN</td>
                            <td data-label="Tên">@item.TenND</td>
                            <td data-label="Email">@item.Email</td>
                            <td data-label="Phone">@item.SDT</td>
                            <td data-label="Địa chỉ">@item.DiaChi</td>
                            <td data-label="Xoá" class="right__iconTable"><a href="#"><img src="~/Areas/Admin/Content/assets/icon-trash-black.svg" alt=""></a></td>
                        </tr>
                    }
                   
                </tbody>
            </table>
        </div>
    </div>
</div>

Shop Ban Sach/ShopQuocViet/Areas/Admin/Views/AdminHome/XemChuDe.cshtml
@using ShopQuocViet.Models
@model List<ChuDe>
@{
    Layout = "~/Areas/Admin/Views/Shared/LayoutAdmin.cshtml";
}

<div class="right__content">
    <div class="right__title">Bảng điều khiển</div>
    <p class="right__desc">Xem Danh Mục</p>
    <div class="right__table">
        <div class="right__tableWrapper">
            <table>
                <thead>
                    <tr>
                        <th>Mã chủ đề</th>
                        <th>Mã danh mục</th>
                        <th>Tên chủ đề</th>
                        <th>Sửa</th>
                        <th>Xoá</th>
                    </tr>
                </thead>

                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td class="stt" data-label="Mã danh mục">@item.MaDM</td>
                            <td data-label="Tên Danh Mục">@item.MaCD</td>
                            <td data-label="Tên chủ đề">@item.TenCD</td>
                            <td data-label="Sửa" class="right__iconTable"><a href=""><img src="~/Areas/Admin/Content/assets/icon-edit.svg" alt=""></a></td>
                            <td data-label="Xoá" class="right__iconTable"><a href=""><img src="~/Areas/Admin/Content/assets/icon-trash-black.svg" alt=""></a></td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

Shop Ban Sach/ShopQuocViet/Areas/Admin/Views/AdminHome/XemDM.cshtml
@using ShopQuocViet.Models
@model List<DanhMuc>
@{
    Layout = "~/Areas/Admin/Views/Shared/LayoutAdmin.cshtml";
}

<div class="right__content">
    <div class="right__title">Bảng điều khiển</div>
    <p class="right__desc">Xem Danh Mục</p>
    <div class="right__table">
        <div class="right__tableWrapper">
            <table>
                <thead>
                    <tr>
                        <th>Mã danh mục</th>
                        <th>Tên danh mục</th>
                        <th>Sửa</th>
                        <th>Xoá</th>
                    </tr>
                </thead>

                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td class="stt" data-label="Mã danh mục">@item.MaDM</td>
                            <td data-label="Tên Danh Mục">@item.TenDM</td>
                            <td data-label="Sửa" class="right__iconTable"><a href=""><img src="~/Areas/Admin/Content/assets/icon-edit.svg" alt=""></a></td>
                            <td data-label="Xoá" class="right__iconTable"><a href=""><img src="~/Areas/Admin/Content/assets/icon-trash-black.svg" alt=""></a></td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

Shop Ban Sach/ShopQuocViet/Areas/Admin/Views/AdminHome/XemDonHang.cshtml
@using ShopQuocViet.Models
@model List<HoaDon>
@{
    Layout = "~/Areas/Admin/Views/Shared/LayoutAdmin.cshtml";
}
<div class="right__content">
    <div class="right__title">Bảng điều khiển</div>
    <p class="right__desc">Xem đơn hàng</p>
    <div class="right__table">
        <div class="right__tableWrapper">
            <table>
                <thead>
                    <tr>
                        <th>Mã hoá đơn</th>
                        <th>Tên khách hàng</th>
                        <th>Tổng tiền</th>
                        <th>Trạng thái v/c</th>
                        <th>Thanh toán</th>
                        <th>Địa chỉ </th>
                        <th>Sđt</th>
                        <th>Ngày</th>
                    </tr>
                </thead>

                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td><a href="@Url.Action("ChiTietHD", "AdminHome", new { MaHD = @item.MaHD })"> @item.MaHD</a></td>
                            <td>@item.TenKH</td>
                            <td>@Convert.ToInt32(@item.TongTien).ToString("N0")</td>
                            <td>@item.TrangThaiVC</td>
                            <td>@item.ThanhToan</td>
                            <td>@item.DiaChi</td>
                            <td>@item.SDT</td>
                            <td>@item.Ngay.ToString().Substring(0, 10)</td>
                        </tr>
                    }

                </tbody>
            </table>
        </div>
    </div>
    </div>
</div>
    <style>
        .right__tableWrapper a {
            color: orange;
        }
    </style>

Shop Ban Sach/ShopQuocViet/Areas/Admin/Views/AdminHome/XemSP.cshtml
@using ShopQuocViet.Models
@model List<TTSach>
@{
    Layout = "~/Areas/Admin/Views/Shared/LayoutAdmin.cshtml";
}

<div class="right__content">
    <div class="right__title">Bảng điều khiển</div>
    <p class="right__desc">Xem sản phẩm</p>
    <div class="right__table">
        <div class="right__tableWrapper">
            <table>
                <thead>
                    <tr>
                        <th>Mã sản phẩm</th>
                        <th>Tên sản phẩm</th>
                        <th>Hình ảnh</th>
                        <th>Tác giả</th>
                        <th>Số trang</th>
                        <th>Giá bán</th>
                        <th>Sửa</th>
                        <th>Xoá</th>
                    </tr>
                </thead>

                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td class="stt" data-label="STT">@Html.ActionLink(@item.MaSach, "XemCTSP", "AdminHome", new { id = @item.MaSach })</td>
                            <td data-label="Tên sản phẩm">Dada Dress</td>
                            <td data-label="Hình ảnh"><img src="~/Content/images/@item.PathAnh" alt=""></td>
                            <td data-label="Tác giả">@item.TacGia</td>
                            <td data-label="Số trang">@item.SoTrang</td>
                            <td data-label="Giá bán">@item.GiaBan</td>
                            <td data-label="Sửa" class="right__iconTable"><a href=""><img src="~/Areas/Admin/Content/assets/icon-edit.svg" alt=""></a></td>
                            <td data-label="Xoá" class="right__iconTable"><a href=""><img src="~/Areas/Admin/Content/assets/icon-trash-black.svg" alt=""></a></td>
                        </tr>
                    }               
                </tbody>
            </table>
        </div>
    </div>
</div>
<style>
    .right__tableWrapper a {
        color: orange;
    }
</style>